<?php

use Illuminate\Database\Seeder;

class ArticleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('article')->insert([

            ['idArt' => 500, 'name' => 'Avocado aguacatado', 'image' => 'aguacate-azul.png', 'price' => 5.95],
            ['idArt' => 501, 'name' => 'Ángel pensativo. Rafael', 'image' => 'angel-rafael-colores.jpg', 'price' => 10.95],
            ['idArt' => 502, 'name' => 'Atún pescado', 'image' => 'atunes-azul.jpg', 'price' => 5.95],
            ['idArt' => 503, 'name' => 'Banana pop. A. Warhol', 'image' => 'banana-warhol-azul.png', 'price' => 10.95],
            ['idArt' => 504, 'name' => 'Barbie girl', 'image' => 'barbie-colores.png', 'price' => 7.95],
            ['idArt' => 505, 'name' => 'Beatles pop', 'image' => 'beatles-amarillo.png', 'price' => 10.95],
            ['idArt' => 506, 'name' => 'El beso. Klimt', 'image' => 'beso-klimt-amarillo.jpg', 'price' => 10.95],
            ['idArt' => 507, 'name' => 'Bicicleta rueda', 'image' => 'bicicletas-verde.jpg', 'price' => 5.95],
            ['idArt' => 508, 'name' => 'Bigote arrocete', 'image' => 'bigotes-negro.jpg', 'price' => 5.95],
            ['idArt' => 509, 'name' => 'Una fantasía', 'image' => 'bosque-negro.jpg', 'price' => 7.95],
            ['idArt' => 510, 'name' => 'Búhos en la noche', 'image' => 'buhos-azul.jpg', 'price' => 5.95],
            ['idArt' => 511, 'name' => 'Burritos coloridos', 'image' => 'burros-verde.jpg', 'price' => 5.95],
            ['idArt' => 512, 'name' => 'Cactus sin desierto', 'image' => 'cactus-azul.jpg', 'price' => 5.95],
            ['idArt' => 513, 'name' => 'Camaleones divertidos', 'image' => 'camaleon-azul.png', 'price' => 5.95],
            ['idArt' => 514, 'name' => 'Cebras en la sabana', 'image' => 'cebras-amarillo.jpg', 'price' => 5.95],
            ['idArt' => 515, 'name' => 'Cerdos y bellotas', 'image' => 'cerditos-azul.jpg', 'price' => 7.95],
            ['idArt' => 516, 'name' => 'A beber beer', 'image' => 'cerveza-colores.png', 'price' => 10.95],
            ['idArt' => 517, 'name' => 'Oktobeer', 'image' => 'cerveza-verde.png', 'price' => 10.95],
            ['idArt' => 518, 'name' => 'Cochecitos', 'image' => 'coches-azul.jpg', 'price' => 5.95],
            ['idArt' => 519, 'name' => 'Cuidado, cocodrilos!', 'image' => 'cocodrilos-gris.jpg', 'price' => 7.95],
            ['idArt' => 520, 'name' => 'Almuerzo espacial', 'image' => 'comida-espacial-negro.jpg', 'price' => 7.95],
            ['idArt' => 521, 'name' => 'Dulce corgi', 'image' => 'corgi-colores.jpg', 'price' => 10.95],
            ['idArt' => 522, 'name' => 'T-Rex grrr', 'image' => 'dinosaurio-azul.jpg', 'price' => 7.95],
            ['idArt' => 523, 'name' => 'Dino baile', 'image' => 'dinosaurio-celeste.png', 'price' => 5.95],
            ['idArt' => 524, 'name' => 'Extinción jurásica', 'image' => 'dinosaurio-colores.png', 'price' => 10.95],
            ['idArt' => 525, 'name' => 'Meteoritos jurásicos', 'image' => 'dinosaurio-colores2.png', 'price' => 10.95],
            ['idArt' => 526, 'name' => 'Baby dino', 'image' => 'dinosaurio-gris.png', 'price' => 7.95],
            ['idArt' => 527, 'name' => 'Mundo jurásico', 'image' => 'dinosaurio-rojo.jpg', 'price' => 7.95],
            ['idArt' => 528, 'name' => 'Donas y coffee', 'image' => 'donuts-azul.jpg', 'price' => 5.95],
            ['idArt' => 529, 'name' => 'Familia de elefantes', 'image' => 'elefantes-azul.jpg', 'price' => 5.95],
            ['idArt' => 530, 'name' => 'Erizos rodantes', 'image' => 'erizos-azul.jpg', 'price' => 5.95],
            ['idArt' => 531, 'name' => 'Despegue espacial', 'image' => 'espacio-colores.png', 'price' => 10.95],
            ['idArt' => 532, 'name' => 'Boo!', 'image' => 'fantasmas-negro.jpg', 'price' => 5.95],
            ['idArt' => 533, 'name' => 'Hot dogs', 'image' => 'fastfood-amarillo.jpg', 'price' => 5.95],
            ['idArt' => 534, 'name' => 'Fast fast, food food!', 'image' => 'fastfood-azul.jpg', 'price' => 5.95],
            ['idArt' => 535, 'name' => 'Pizza chunga', 'image' => 'fastfood-azul2.jpg', 'price' => 5.95],
            ['idArt' => 536, 'name' => 'Sabrosa pizza', 'image' => 'fastfood-azul3.jpg', 'price' => 5.95],
            ['idArt' => 537, 'name' => 'Soda o chips?', 'image' => 'fastfood-colores.png', 'price' => 5.95],
            ['idArt' => 538, 'name' => 'Burguer Queen', 'image' => 'fastfood-rojo.jpg', 'price' => 5.95],
            ['idArt' => 539, 'name' => 'Flamencos flamencos', 'image' => 'flamencos-azul.jpg', 'price' => 5.95],
            ['idArt' => 540, 'name' => 'Flamenco y flamenca', 'image' => 'flamencos-verde.jpg', 'price' => 7.95],
            ['idArt' => 541, 'name' => 'Bajo el mar...!', 'image' => 'fondomarino-colores.png', 'price' => 7.95],
            ['idArt' => 542, 'name' => 'Classic foodtrucks', 'image' => 'foodtrucks-azul.jpg', 'price' => 7.95],
            ['idArt' => 543, 'name' => 'Fiesta de foodtrucks', 'image' => 'foodtrucks-gris.jpg', 'price' => 7.95],
            ['idArt' => 544, 'name' => 'Frida', 'image' => 'fridakahlo-azul.jpg', 'price' => 10.95],
            ['idArt' => 545, 'name' => 'Gooooool', 'image' => 'futbol-colores.png', 'price' => 10.95],
            ['idArt' => 546, 'name' => 'Chute (y gol)', 'image' => 'futbol-verde.jpg', 'price' => 5.95],
            ['idArt' => 547, 'name' => 'Delirio gatuno', 'image' => 'gatos-azul.jpg', 'price' => 5.95],
            ['idArt' => 548, 'name' => 'Girasoles. Van Gogh', 'image' => 'girasoles-vangogh-colores.jpg', 'price' => 10.95],
            ['idArt' => 549, 'name' => 'El Grinch', 'image' => 'grinch-colores.jpg', 'price' => 10.95],
            ['idArt' => 550, 'name' => 'Red and green Chili Peppers', 'image' => 'guindillas-amarillo.jpg', 'price' => 5.95],
            ['idArt' => 551, 'name' => 'Red and green Chili Peppers again', 'image' => 'guindillas-azul.jpg', 'price' => 5.95],
            ['idArt' => 552, 'name' => 'Potter and friends', 'image' => 'harrypotter-azul.jpg', 'price' => 10.95],
            ['idArt' => 553, 'name' => 'Magia y hechicería', 'image' => 'harrypotter-houses-negro.jpg', 'price' => 7.95],
            ['idArt' => 554, 'name' => 'Sabores mil', 'image' => 'helados-azul.png', 'price' => 5.95],
            ['idArt' => 555, 'name' => 'Helados classic', 'image' => 'helados-azul2.png', 'price' => 5.95],
            ['idArt' => 556, 'name' => 'Gafa and pastis', 'image' => 'hipsters-azul.jpg', 'price' => 7.95],
            ['idArt' => 557, 'name' => 'Hipsters con frío', 'image' => 'hipsters-gris.jpg', 'price' => 7.95],
            ['idArt' => 558, 'name' => 'Hipsters campestres', 'image' => 'hipsters-verde.jpg', 'price' => 7.95],
            ['idArt' => 559, 'name' => 'Canal Huevo', 'image' => 'huevos-fritos-azul.jpg', 'price' => 5.95],
            ['idArt' => 560, 'name' => 'El huevo o la gallina', 'image' => 'huevos-pollos-rojo.png', 'price' => 10.95],
            ['idArt' => 561, 'name' => 'Koalas', 'image' => 'koalas-rojo.png', 'price' => 5.95],
            ['idArt' => 562, 'name' => 'Koalas en verde', 'image' => 'koalas-verde.png', 'price' => 5.95],
            ['idArt' => 563, 'name' => 'Preparados para dormir', 'image' => 'leones-negro.jpg', 'price' => 5.95],
            ['idArt' => 564, 'name' => 'El saber ocupa lugar', 'image' => 'libros-azul.png', 'price' => 5.95],
            ['idArt' => 565, 'name' => 'Los del Fari', 'image' => 'limones-colores.png', 'price' => 5.95],
            ['idArt' => 566, 'name' => 'Los loros', 'image' => 'loros-amarillo.jpg', 'price' => 5.95],
            ['idArt' => 567, 'name' => '... Borrás', 'image' => 'magia-gris.png', 'price' => 5.95],
            ['idArt' => 568, 'name' => 'Ding ding', 'image' => 'mariobros-rojo.jpg', 'price' => 10.95],
            ['idArt' => 569, 'name' => 'Mexico lindo', 'image' => 'mascaraslucha-gris.jpg', 'price' => 7.95],
            ['idArt' => 570, 'name' => 'Cura médica', 'image' => 'medicina-azul.png', 'price' => 5.95],
            ['idArt' => 571, 'name' => 'Old Mickey', 'image' => 'mickey-gris.jpg', 'price' => 7.95],
            ['idArt' => 572, 'name' => 'New Mickey', 'image' => 'mickey-gris2.jpg', 'price' => 7.95],
            ['idArt' => 573, 'name' => 'Mona Lisa. Da Vinci', 'image' => 'monalisa-colores.jpg', 'price' => 10.95],
            ['idArt' => 574, 'name' => 'Monos monos', 'image' => 'monos-colores.png', 'price' => 5.95],
            ['idArt' => 575, 'name' => 'Vespa en gris', 'image' => 'motos-gris.jpg', 'price' => 5.95],
            ['idArt' => 576, 'name' => 'Vespa en verde', 'image' => 'motos-verde.jpg', 'price' => 5.95],
            ['idArt' => 577, 'name' => 'It´s Nessie!', 'image' => 'nessie-gris.jpg', 'price' => 5.95],
            ['idArt' => 578, 'name' => 'David...?', 'image' => 'nomosJardin-verde.png', 'price' => 5.95],
            ['idArt' => 579, 'name' => 'Nubes celestiales', 'image' => 'nubes-azul.jpg', 'price' => 5.95],
            ['idArt' => 580, 'name' => 'Una, dos, tres...', 'image' => 'ovejas-gris.jpg', 'price' => 5.95],
            ['idArt' => 581, 'name' => 'Pacman', 'image' => 'pacman-negro.jpg', 'price' => 7.95],
            ['idArt' => 582, 'name' => 'La Pantera Rosa', 'image' => 'panterarosa-colores.png', 'price' => 10.95],
            ['idArt' => 583, 'name' => 'Cuá cuá', 'image' => 'patitos-azul.png', 'price' => 5.95],
            ['idArt' => 584, 'name' => 'Pelícanos', 'image' => 'pelicanos-azul.png', 'price' => 5.95],
            ['idArt' => 585, 'name' => 'Perros', 'image' => 'perros-azul.jpg', 'price' => 5.95],
            ['idArt' => 586, 'name' => 'Los perros de Bowie', 'image' => 'perros-verde.jpg', 'price' => 5.95],
            ['idArt' => 587, 'name' => 'Más perros', 'image' => 'perros-verde2.jpg', 'price' => 5.95],
            ['idArt' => 588, 'name' => 'Picasso', 'image' => 'picasso-colores.png', 'price' => 10.95],
            ['idArt' => 589, 'name' => 'Tropical', 'image' => 'pinias-azul.jpg', 'price' => 5.95],
            ['idArt' => 590, 'name' => 'Jaws', 'image' => 'playa-colores.png', 'price' => 7.95],
            ['idArt' => 591, 'name' => 'Meowth', 'image' => 'pokemon-meowth-blanco.jpg', 'price' => 7.95],
            ['idArt' => 592, 'name' => 'Dos pokeballs', 'image' => 'pokemon-pokeball-blanco.jpg', 'price' => 7.95],
            ['idArt' => 593, 'name' => 'Viva Woodstock', 'image' => 'psicodelia-colores.jpg', 'price' => 5.95],
            ['idArt' => 594, 'name' => 'Octopusy', 'image' => 'pulpos-azul.png', 'price' => 5.95],
            ['idArt' => 595, 'name' => 'Queen', 'image' => 'queen-colores.jpg', 'price' => 10.95],
            ['idArt' => 596, 'name' => 'Rick y Morty', 'image' => 'rickymorty-verde.jpg', 'price' => 10.95],
            ['idArt' => 597, 'name' => 'Sandías', 'image' => 'sandia-amarillo.jpg', 'price' => 5.95],
            ['idArt' => 598, 'name' => 'Space invaders', 'image' => 'spaceinvaders-azul.jpg', 'price' => 7.95],
            ['idArt' => 599, 'name' => 'St Patrick', 'image' => 'stpatrick-verde.jpg', 'price' => 7.95],
            ['idArt' => 600, 'name' => 'Fondo marino', 'image' => 'submarinos-azul.png', 'price' => 5.95],
            ['idArt' => 601, 'name' => 'Mario Bros.', 'image' => 'supermario-gris.jpg', 'price' => 5.95],
            ['idArt' => 602, 'name' => 'Suricatos', 'image' => 'suricato-azul.png', 'price' => 5.95],
            ['idArt' => 603, 'name' => 'Maki o nigiri', 'image' => 'sushi-azul.jpg', 'price' => 5.95],
            ['idArt' => 604, 'name' => 'Tiburones al ataque', 'image' => 'tiburones-azul.jpg', 'price' => 5.95],
            ['idArt' => 605, 'name' => 'Tortugas', 'image' => 'tortugas-negro.png', 'price' => 5.95],
            ['idArt' => 606, 'name' => 'Tucán', 'image' => 'tucanes-rojo.jpg', 'price' => 7.95],
            ['idArt' => 607, 'name' => 'Unicornio y mariposas', 'image' => 'unicornio-colores.jpg', 'price' => 7.95],
            ['idArt' => 608, 'name' => 'Mundo fantasía', 'image' => 'unicornios-colores.jpg', 'price' => 7.95],
            ['idArt' => 609, 'name' => 'MacDonald', 'image' => 'vacas-granja-colores.jpg', 'price' => 7.95],
            ['idArt' => 610, 'name' => 'Willy y amigas liberadas', 'image' => 'willy-amarillo.png', 'price' => 7.95],
            ['idArt' => 611, 'name' => 'Zelda', 'image' => 'zelda-negro.jpg', 'price' => 5.95],
            ['idArt' => 612, 'name' => 'Amarillos', 'image' => 'plano-amarillo.jpg', 'price' => 5.95]

        ]);
    }
}
